language: android
sudo: false
android:
  components:
    - android-23
    - build-tools-24.0.2
    - extra
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17
jdk:
  - oraclejdk8
script: ./gradlew testDebug
